- broken grails tag in importer view broke war generation:
Error executing script War: : org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Grails tag [importer:] was not closed at /WEB-INF/grails-app/views/importer/step2.gsp:40
gant.TargetExecutionException: : org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Grails tag [importer:] was not closed at /WEB-INF/grails-app/views/importer/step2.gsp:40